language: dart
dart: [stable, dev]

cache:
  timeout: 300
  bundler: true
  directories:
  - $HOME/.pub-cache
  - $HOME/.nvm
  - $HOME/.rvm
  - node_modules

env:
  global:
    - JEKYLL_ENV=production
    - TZ=US/Pacific # normalize build timestamp
  matrix:
    - TASK="./tool/translator/build.sh --check-links"
#   - TASK="./tool/check-code.sh"
    - TASK="./tool/analyze-and-test-examples.sh"

before_install:
  - source ./tool/env-set.sh
  - ./tool/before-install.sh

install:
  - ./tool/install.sh
  - ./tool/shared/write-ci-info.sh -v

script: $TASK

deploy:
  - provider: script
    script: ./tool/translator/deploy-cn.sh
    skip_cleanup: true
    on:
      repo: cfug/dart.cn
      branch: master
      condition: $TASK == *build*
#     condition: $TASK == *tool/build.sh* && $TRAVIS_DART_VERSION == stable && $TRAVIS_EVENT_TYPE == push

# Only run Travis jobs for named branches (to avoid double builds for each PR)
branches:
  only: [master, /^\d\.x$/, /^\d-dev$/, /travis-build/]
